kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 32001
    protocol: TCP
  - containerPort: 443
    hostPort: 32011
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 32002
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 443
    hostPort: 32012
    listenAddress: "127.0.0.1"
    protocol: TCP